### ISSUE TITLE
historical_capes.csv missing?

### ISSUE THREAD

**Issue by gorkang** [KaroRonty/MomentumAndValuation#1]
Thanks for the interesting post. 

When trying to run your code, can't see where `historical_capes.csv` is...

```
# Read historical CAPE data from Barclay's
capedata <- read.csv("historical_capes.csv",
                     check.names = FALSE)
```

**Comment by KaroRonty** [comment]
It can be downloaded here by checking all the countries and clicking "Export": http://shiller.barclays.com/SM/12/en/indices/static/historic-ratios.app
